import { test, expect } from '@playwright/test';
import LoginPage from '../../pageobjects/LoginPage/login.page';
import HomePage from '../../pageobjects/HomePage/home.page';
import CommonPage from '../../pageobjects/CommonPage/common.page';
import AddToCartPage from '../../pageobjects/AddToCartPage/addtocart.page';
import CheckoutPage from '../../pageobjects/CheckoutPage/checkout.page';
import CheckoutDetailsPage from '../../pageobjects/CheckoutPage/checkoutDetails.page';
import SuccessCheckoutPage from '../../pageobjects/CheckoutPage/successCheckout.page';
import CheckoutData from '../../data/CheckoutData/checkout.data.json' assert { type: 'json' };
import LoginData from '../../data/LoginData/login.data.json' assert { type: 'json' };
test.describe('Checkout Page Test', () => {
    test('Validate total price in CheckOutPage after adding items from HomePage to AddToCartPage', async ({ page }) => {
        const loginPageObject = new LoginPage(page);
        await loginPageObject.verifyLogin(LoginData.valid_username, LoginData.valid_password);
        const homePageObject = new HomePage(page);
        await homePageObject.verifyclickallAddToCartBtn();
        const commonPageObject = new CommonPage(page);
        await commonPageObject.cartLogo.click();
        const addToCartPageObject = new AddToCartPage(page);
        await addToCartPageObject.checkoutBtn.click();
        const checkoutPageObject = new CheckoutPage(page);
        await checkoutPageObject.setUserCheckoutInfo(CheckoutData.user_first_name, CheckoutData.user_last_name, CheckoutData.postal_code);
        await checkoutPageObject.continueCartInfoBtn.click();
        const checkoutDetailsPageObject = new CheckoutDetailsPage(page);
        const actual = await checkoutDetailsPageObject.totalPriceLabel.textContent();
        console.log('Total Price', actual);
        expect(actual).toBe('Total: $140.34');
    });
    test('Validate the pressing of cancel button of Checkout Info Details Given Page', async ({ page }) => {
        const loginPageObject = new LoginPage(page);
        await loginPageObject.verifyLogin(LoginData.valid_username, LoginData.valid_password);
        const homePageObject = new HomePage(page);
        await homePageObject.verifyclickallAddToCartBtn();
        const commonPageObject = new CommonPage(page);
        await commonPageObject.cartLogo.click();
        const addToCartPageObject = new AddToCartPage(page);
        await addToCartPageObject.checkoutBtn.click();
        const checkoutPageObject = new CheckoutPage(page);
        await checkoutPageObject.setUserCheckoutInfo(CheckoutData.user_first_name, CheckoutData.user_last_name, CheckoutData.postal_code);
        await checkoutPageObject.cancelCartInfoBtn.click();
        console.log('cartPageUrl', page.url());
        await expect(page).toHaveURL('https://www.saucedemo.com/v1/cart.html');
    });
    test('Validate the checkout operation completes after click on Finish button of CheckOutPage', async ({ page }) => {
        const loginPageObject = new LoginPage(page);
        await loginPageObject.verifyLogin(LoginData.valid_username, LoginData.valid_password);
        const homePageObject = new HomePage(page);
        await homePageObject.verifyclickallAddToCartBtn();
        const commonPageObject = new CommonPage(page);
        await commonPageObject.cartLogo.click();
        const addToCartPageObject = new AddToCartPage(page);
        await addToCartPageObject.checkoutBtn.click();
        const checkoutPageObject = new CheckoutPage(page);
        await checkoutPageObject.setUserCheckoutInfo(CheckoutData.user_first_name, CheckoutData.user_last_name, CheckoutData.postal_code);
        await checkoutPageObject.continueCartInfoBtn.click();
        const checkoutDetailsPageObject = new CheckoutDetailsPage(page);
        await checkoutDetailsPageObject.finishCheckoutBtn.click();
        const successCheckoutPageObject = new SuccessCheckoutPage(page);
        const actual = await successCheckoutPageObject.verifyCheckoutOperation();
        expect(actual).toBeTruthy();
    });
    test('Validate the checkout operation cancels after click on Cancel button of CheckOutPage', async ({ page }) => {
        const loginPageObject = new LoginPage(page);
        await loginPageObject.verifyLogin(LoginData.valid_username, LoginData.valid_password);
        const homePageObject = new HomePage(page);
        await homePageObject.verifyclickallAddToCartBtn();
        const commonPageObject = new CommonPage(page);
        await commonPageObject.cartLogo.click();
        const addToCartPageObject = new AddToCartPage(page);
        await addToCartPageObject.checkoutBtn.click();
        const checkoutPageObject = new CheckoutPage(page);
        await checkoutPageObject.setUserCheckoutInfo(CheckoutData.user_first_name, CheckoutData.user_last_name, CheckoutData.postal_code);
        await checkoutPageObject.continueCartInfoBtn.click();
        const checkoutDetailsPageObject = new CheckoutDetailsPage(page);
        await checkoutDetailsPageObject.cancelCheckoutBtn.click();
        console.log('homePageUrl', page.url());
        await expect(page).toHaveURL('https://www.saucedemo.com/v1/inventory.html');
    });
    CheckoutData.checkoutinfodetails.forEach((user) => {
        test(`Validate Checkout Info Details from the JSON file from Checkout Info Details Page: ${user.firstname}`, async ({ page }) => {
            const loginPageObject = new LoginPage(page);
            await loginPageObject.verifyLogin(LoginData.valid_username, LoginData.valid_password);
            const homePageObject = new HomePage(page);
            await homePageObject.verifyclickallAddToCartBtn();
            const commonPageObject = new CommonPage(page);
            await commonPageObject.cartLogo.click();
            const addToCartPageObject = new AddToCartPage(page);
            await addToCartPageObject.checkoutBtn.click();
            const checkoutPageObject = new CheckoutPage(page);
            await checkoutPageObject.setUserCheckoutInfo(user.firstname, user.lastname, user.postalcode);
            await checkoutPageObject.continueCartInfoBtn.click();
            const checkoutDetailsPageObject = new CheckoutDetailsPage(page);
            const actual = await checkoutDetailsPageObject.totalPriceLabel.textContent();
            console.log('Total Price', actual);
            expect(actual).toBe('Total: $140.34');
        });
    });
});